# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e85ea70e847e67ebb47e43648432e05e59f6b8244b6d3ede96a9877109399e7b7888b4a0b6cca75ba6af39158bc7637c74310868605ba24ed39d6e33acbd9154

test:
  secret_key_base: 9b3b126246f52ad503f548000f0323136fc53207b40fc4024eeb4df7f50b73adfa7d4c35c38c742a2c149d30e10f853c9d8ec378a6612ca0f7de1dce12ab1f53

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
